name: Main
on:
  push:
    branches:
      - master
jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Crystal shard cache
        uses: actions/cache@v1
        with:
          path: lib
          key: ${{ runner.os }}-shards-${{ hashFiles('**/shard.yml') }}
          restore-keys: |
            ${{ runner.os }}-shards-

      - name: Install dependencies
        run: shards install

      - name: Run ameba
        run: bin/ameba

  tests:
    name: Tests
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Crystal shard cache
        uses: actions/cache@v1
        with:
          path: lib
          key: ${{ runner.os }}-shards-${{ hashFiles('**/shard.yml') }}
          restore-keys: |
            ${{ runner.os }}-shards-

      - name: Install dependencies
        run: shards install

      - name: Run tests
        run: crystal spec
