name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: shards install
    - name: Run ameba
      run: bin/ameba
    - name: Run tests
      run: crystal spec
